server:
  port: 10510
spring:
  main:
    banner-mode: "off"
  profiles:
    active: dev
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.3.9/table_to_json_test?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    #    username: root
    #    password: robot_123456#
    url: jdbc:postgresql://192.168.3.9/uh_courses
    username: postgres
    password: robot_123456#